version: '3'

services:
    web:
        build: .
        command: bundle exec rails s -p 3000 -b 0.0.0.0
        ports:
            - "3000:3000"
        volumes:
            - ".:/usr/src/site"
        environment:
            DB_HOST: postgres
            DB_USERNAME: postgres
            DB_PASSWORD: password
            DB_NAME: shared

networks:
    default:
        external:
            name: db-network
