version: '2'

networks:
    bridge:
        driver: bridge

services:
    db:
        image: postgres
        volumes:
            - "./tmp/db:/var/lib/postgresql/data"
        environment:
            POSTGRES_DB: blog
            POSTGRES_PASSWORD: passbuildword
        networks:
            - bridge
    web:
        build: .
        command: bundle exec rails s -p 3000 -b 0.0.0.0
        ports:
            - "3000:3000"
        depends_on:
            - db
        volumes:
            - ".:/usr/src/blog"
        environment:
            DB_HOST: db
            DB_USERNAME: postgres
            DB_PASSWORD: password
            DB_NAME: blog
        networks:
            - bridge
